ci: should be tested with minimum tools as possible on macos

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,14 +38,14 @@ jobs:
       - name: Run linting tasks
         run: set -eux; make lint
 
-  integration-macos-molecule:
+  integration-macos-native:
     name: Integration on macOS
-    runs-on: macos-${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
     strategy:
-      max-parallel: 4
+      fail-fast: false
       matrix:
-        os: ["12"]
-        scenario: ["default-macos-on-localhost"]
+        os:
+          - macos-12
     steps:
       - name: Check out the codebase
         uses: actions/checkout@v3
@@ -59,13 +59,52 @@ jobs:
       - name: Install test dependencies
         run: export INSTALL_POETRY=false; make install
 
-      - name: Run molecule tests
-        run: poetry run molecule test --scenario-name "${SCENARIO}" -- -vvv --become
+      - name: Test the playbook
+        run: make test
         env:
-          SCENARIO: ${{ matrix.scenario }}
-          PY_COLORS: '1'
-          ANSIBLE_FORCE_COLOR: '1'
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Idempotence check
+        # This `shell` line is required to get around a known issue: https://github.com/actions/runner/issues/241#issuecomment-745902718
+        # ! Not supported by macOS !
+        # shell: 'script -q -e -c "bash {0}"'
+        # run: make test-idempotent
+        run: |
+          IDEMPOTENCE=$(mktemp)
+          cd tests && poetry run ansible-playbook test.yml | tee -a ${IDEMPOTENCE}
+          tail ${IDEMPOTENCE} \
+            | grep -q 'changed=0.*failed=0' \
+            && (echo 'Idempotence test: pass' && exit 0) \
+            || (echo 'Idempotence test: fail' && exit 1)
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
+          ANSIBLE_STDOUT_CALLBACK: 'unixy'
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  #  integration-macos-molecule:
+  #    name: Integration on macOS
+  #    runs-on: macos-${{ matrix.os }}
+  #    strategy:
+  #      max-parallel: 4
+  #      matrix:
+  #        os: ["12"]
+  #        scenario: ["default-macos-on-localhost"]
+  #    steps:
+  #      - name: Check out the codebase
+  #        uses: actions/checkout@v3
+  #      - name: Uninstall built-in homebrew
+  #        run: sh tests/uninstall-homebrew.sh
+  #      - name: Install poetry
+  #        uses: gi0baro/setup-poetry-bin@v1
+  #      - name: Install test dependencies
+  #        run: export INSTALL_POETRY=false; make install
+  #      - name: Run molecule tests
+  #        run: poetry run molecule test --scenario-name "${SCENARIO}" -- -vvv --become
+  #        env:
+  #          SCENARIO: ${{ matrix.scenario }}
+  #          PY_COLORS: '1'
+  #          ANSIBLE_FORCE_COLOR: '1'
+  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   integration-linux-molecule:
     name: Integration on Linux
@@ -103,7 +142,8 @@ jobs:
     if: github.event.inputs.shouldPublish == 'yes' || github.ref == 'refs/heads/master'
     needs:
       - lint
-      - integration-macos-molecule
+      - integration-macos-native
+      # - integration-macos-molecule
       - integration-linux-molecule
     runs-on: ubuntu-latest
     steps:
